# Generated by Django 4.2.11 on 2026-06-17 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('protocol', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('OTHER', 'OTHER')], default='OTHER', max_length=10)),
                ('length', models.IntegerField()),
                ('is_anomaly', models.BooleanField(default=False)),
                ('attack_type', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
